SELECT regions.region_ID, countries.region_id
from REGIONS, COUNTRIES
WHERE regions.region_ID = countries.region_ID;

SELECT A.DEPARTMENT_ID, A.DEPARTMENT_NAME, B.FIRST_NAME, B.DEPARTMENT_ID
from DEPARTMENTS A, EMPLOYEES B
where A.manager_ID = B.manager_ID;

select *
from EMPLOYEES, DEPARTMENTS;

SELECT A.EMPLOYEE_ID, A.FIRST_NAME, B.DEPARTMENT_ID, B.DEPARTMENT_NAMEx
from EMPLOYEES A, DEPARTMENTS B
where A.DEPARTMENT_ID = B.DEPARTMENT_ID;

SELECT A.DEPARTMENT_ID, A.DEPARTMENT_NAME, B.STREET_ADDRESS, B.POSTAL_CODE, B.CITY
FROM DEPARTMENTS A, LOCATIONS B
where A.LOCATION_ID = B.LOCATION_ID;

SELECT B.DEPARTMENT_ID, A.DEPARTMENT_NAME, B.FIRST_NAME
from DEPARTMENTS A, EMPLOYEES B
where A.MANAGER_ID = B.EMPLOYEE_ID
order by A.DEPARTMENT_ID;

SELECT A.EMPLOYEE_ID, A.FIRST_NAME , B.DEPARTMENT_NAME, C.JOB_TITLE
FROM EMPLOYEES A, DEPARTMENTS B, JOBS C
WHERE B.DEPARTMENT_ID = A.DEPARTMENT_ID
AND A.JOB_ID = C.JOB_ID
order by A.EMPLOYEE_ID;

SELECT A.DEPARTMENT_ID, A.DEPARTMENT_NAME, B.CITY, C.COUNTRY_NAME
from DEPARTMENTS A, LOCATIONS B, COUNTRIES C
WHERE B.COUNTRY_ID = C.COUNTRY_ID
AND A.LOCATION_ID = B.LOCATION_ID
ORDER by A.department_ID;

SELECT A.EMPLOYEE_ID, A.FIRST_NAME, B.EMPLOYEE_ID, B.FIRST_NAME
FROM EMPLOYEES A, EMPLOYEES B
WHERE A.MANAGER_ID = B.EMPLOYEE_ID

